version: '3.8'

services:
  api_users:
    container_name: backend_users
    build: .
    ports:
      - 3001:3001
    environment: 
      PORT: 3001
    env_file: .env
    volumes:
      - ./:/code
      - node_modules:/code/node_modules
    networks: 
      - backend_users
      - siged_backend
    depends_on:
      - db_users

  db_users:
    container_name: db_users
    image: mongo:4.4
    restart: always
    ports:
      - "3009:27017"
    environment:
      MONGO_INITDB_DATABASE: root-db
    env_file: .env
    volumes:
      - ./db/.dbshell:/home/mongodb/.dbshell
      - mongodb:/data/db
    networks: 
      - backend_users

volumes: 
  node_modules:
  mongodb:

networks: 
  backend_users:
  siged_backend:
    external: true