name: Metrics
on: [push, pull_request]

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Executar testes
        run:  docker network create siged_backend && docker-compose run api_users bash -c  "yarn && yarn jest --coverage --forceExit --outputFile=test-results.json --json"

      - name: Coletar métricas
        run: python parser.py fga-eps-mds_${{ github.event.repository.name }}