name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: siged-users #Must be unique in Heroku
          heroku_email: epssiged@gmail.com
          usedocker: true
          env_file: ".env"

      - name: Set env file
        run: |
          cd 2021-2-SiGeD-Users
          git checkout master
          git checkout .
          git pull origin master
          cp main.env .env